### ISSUE TITLE
Terminal Bell Sound

### ISSUE THREAD

**Issue by alindesign** [felixse/FluentTerminal#113]
Hi there,
After 1 week of using, this beautiful terminal, have find a stressing thing that happen on each tab completition (for example), does it support, mute or change bell sound?

**Comment by ericcornelissen** [comment]
What profile are you using @alindesign (WSL, CMD, PowerShell, Bash)?

- CMD: [link 1 (errorfixer.co)](https://errorfixer.co/disable-cmd-powershell-beep-sounds/)
- WSL: [link 1 (stackexchange)](https://stackoverflow.com/questions/36724209/disable-beep-of-linux-bash-on-windows-10)
- PowerShell: [link 1 (reddit)](https://www.reddit.com/r/Windows10/comments/6dv1on/disabling_all_sounds_in_powershell/), [link 2 (stackexchange)](https://superuser.com/questions/10575/turning-off-the-cmd-window-beep-sound), [link 3 (errorfixer.co)](https://errorfixer.co/disable-cmd-powershell-beep-sounds/)
- Bash: [link 1 (stackexchange)](https://superuser.com/questions/1108120/how-to-disable-bash-on-windows-notification-sound-effect)

I didn't test those for Bash and WSL, but the ones for CMD and PowerShell should work. Either way, I think your problem relates to the CLI you're using rather than FluentTerminal 😉

**Comment by felixse** [comment]
@ericcornelissen is right. There is an option in xterm.js we could use to disable sounds, but not all shells are respecting this (e.g. powershell/psreadline doesn't care) so it would be confusing if we provide a option that is not really reliable.

**Comment by alindesign** [comment]
@ericcornelissen Thanks for links, yes i have do that, but look like they don't care about it and still "throw" that bell 😂

**Comment by Riebart** [comment]
I use Ubuntu 1804 WSL, and the bash config for disabling the bell sound works as expected.

**Comment by yap770813901** [comment]
The system sound is not cool. I look forward to add a button to change it.

**Comment by skipmeister123** [comment]
I guess "not cool" is relative. Can you elaborate?

**Comment by enify** [comment]
I think add a global button to disable the bell is necessary!
When I use WSL in FluentTerminal, I got some different situations：
- After I add `set bell-style visible` in `~/.inputrc`, the `bash` followed this rule, but in `zsh` not work.
- When I `ssh` to a remote server, this rule invalid, means I also need to add this rule in remote server to disable the beel. It's not very convenient to do this....😂

**Comment by felixse** [comment]
Added with https://github.com/felixse/FluentTerminal/pull/437
