### ISSUE TITLE
Share your custom profile

### ISSUE THREAD

**Issue by Sharlaan** [felixse/FluentTerminal#129]
Nice integration for windows, thanks !

Can you share this nice shell profile showed in screenshot in README ? please

Would also help users setting their own.

**Comment by felixse** [comment]
I'm using PowerShell with the [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh) plugin installed. The prompt theme is Agnoster, and my color theme is [Argonaut](https://github.com/effkay/iTerm-argonaut/)

**Comment by Sharlaan** [comment]
Thanks for the enswer, but i'm newbie with PS, i'm failing so far to reproduce your Theme setup....

I've followed instructions from Oh-my-posh repo to install it along posh-git, but produced the config file seems to apply only to the regular PS console, not FluentTerminal ...
... and it does pretty badly :
https://i.imgur.com/QRxa4fv.png

Same for the color scheme, 0 instruction.

I admit i'm kinda lost between configurations for FluentTerminal, PS, ConEmu, (and .bashrc for aliases)
Some directions on how to use existing themes, color schemes on the README would help, thanks.

**Comment by felixse** [comment]
Looks like you edited the wrong profile file. There are multiple, based on which terminal is used. The easiest way is to edit it directly in Fluent Terminal, e.g. with `code $profile`(or any other editor instead of vscode). 

The color theme is something you would setup in the settings of Fluent Terminal. In 'Settings -> Themes' you can import the .itermcolors file I have linked. 

Aliases are depending on the shell you want to use. Since it looks like you want to use PowerShell you would need to add them to your profile ($profile) file as well. [Here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/set-alias?view=powershell-6) is some documentation on how to set up aliases for PowerShell.

**Comment by felixse** [comment]
You need a special patched font which includes these icons. You can find a lot prepatched fonts here: https://nerdfonts.com/#downloads

**Comment by Sharlaan** [comment]
Ok i downloaded and installed the Meslo....otf font file, then in FluentTerminal Settings > Terminal > Font Family, select `Meslo LGM NF for Powerline`

Hope it helps for other poeple.
