### ISSUE TITLE
Add option to disable tray icon

### ISSUE THREAD

**Issue by ericcornelissen** [felixse/FluentTerminal#137]
In my workflow, I would prefer that closing all FluentTerminal windows stops the process entirely rather then keeping it open in tray.

I'm interested in implementing this myself, just wanted to confirm if this is a desired feature first 🙂

**Comment by jonaskuske** [comment]
Chiming in here, I'd also like it if I could disable the tray icon but still run Fluent Terminal in the background – just to remove some clutter from the taskbar.

**Comment by felixse** [comment]
> In my workflow, I would prefer that closing all FluentTerminal windows stops the process entirely rather then keeping it open in tray.
> 
> I'm interested in implementing this myself, just wanted to confirm if this is a desired feature first 🙂

Sounds like a reasonable feature, PRs are always welcome 👍 


> Chiming in here, I'd also like it if I could disable the tray icon but still run Fluent Terminal in the background – just to remove some clutter from the taskbar.

This could be pretty hard since the Tray Icon is our way out of the sandbox that we need in order to create shell processes

**Comment by skipmeister123** [comment]
What about a service, rather than a trayapp?

--
Hans Kokx
On 11/19/2018 4:44:08 AM, Felix <notifications@github.com> wrote:
In my workflow, I would prefer that closing all FluentTerminal windows stops the process entirely rather then keeping it open in tray.
I'm interested in implementing this myself, just wanted to confirm if this is a desired feature first 🙂
Sounds like a reasonable feature, PRs are always welcome 👍
Chiming in here, I'd also like it if I could disable the tray icon but still run Fluent Terminal in the background – just to remove some clutter from the taskbar.
This could be pretty hard since the Tray Icon is our way out of the sandbox that we need in order to create shell processes

**Comment by felixse** [comment]
Might work, but that would be a bit of work
