### ISSUE TITLE
How to integrate with cmder?

### ISSUE THREAD

**Issue by sixtar** [felixse/FluentTerminal#148]
This app is perfect,but I'm used to cmder(using linux style commands in cmd).How can I put them together?

**Comment by kamenminkov** [comment]
I was wondering the same thing. With a little trial and error, I came up with the following:

```
@echo off
title fterm
cmd /k C:\cmder\vendor\init.bat
```
... in a batch file. Then, from FT, point to that batch file instead of directly to cmder's `init.bat`:

![image](https://user-images.githubusercontent.com/16286572/49501872-8e30dc00-f87c-11e8-90ed-2cc8dc76d337.png)

Doesn't matter where you place it, seems like the path to `init.bat` has to be absolute.
I don't know why pointing directly to `init.bat` doesn't work, but here we are. The thing I can't figure out myself is why passing the current directory (i.e. from Explorer) doesn't work, but this seems like a more general issue.

**Comment by ericcornelissen** [comment]
That guide works like a charm 👌 I guess with that solution the issue can be closed @felixse? Perhaps it is an idea to put this (and other questions such as #146) in a FAQ somewhere?

**Comment by felixse** [comment]
Nice guide 👍 
Yeah, I think we should start a wiki. We could also move the build instructions in readme.md to make it less intimidating

**Comment by skipmeister123** [comment]
Seems like a great idea.
--
Hans Kokx

**Comment by felixse** [comment]
I created  a [FAQ page](https://github.com/felixse/FluentTerminal/wiki/FAQ)
The wiki is open for contribution by everyone, let's see how that works out 😅
