### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by sinnlosername** [felixse/FluentTerminal#179]
FluentTerminal (latest version) crashes quite often for me. It always happens like the following:

1. The terminal hangs. You can still switch tabs and go into settings, but you can't type any text into it and you will not see any output text anymore.
-> App restart
2. After restarting it will do the same as in 1. This means you simply see nothing at all in the terminal because no text ever reaches you.
-> App restart
3. Now it works like it should again. Everything loads and works fine

This problem occurs multiple times per day to me. There are 2 errors in the event log everytime it happened. I've but the information from the "General" and "Details" tab of the windows event browser into it, however thanks to my pc language many texts are on german. I hope Google Translate helps out on this: https://p.reflex.rip/uhuv.xml

**Comment by felixse** [comment]
Ok, so for some reason the port we need for the websocket between UWP and the WebView is used twice (we use it also as a key for a dictionary). This might happen if there is something blocking the websocket from opening. Then the next terminal would try the same port (since it is still free) and the dict will throw your attached exception. Do you have any anti virus running that might interfere?

**Comment by sinnlosername** [comment]
Windows Defender is running, however it also happened on the pc of a friend who's using bitdefender, so I don't think it's related to the antivirus.

**Comment by yuguorui** [comment]
The same here, only installed Windows Defender.

**Comment by Powerrrrrr** [comment]
This bug fixed?

**Comment by felixse** [comment]
Probably. Did you experience something like this?
