### ISSUE TITLE
Add option to notify that text has been copied

### ISSUE THREAD

**Issue by felixse** [felixse/FluentTerminal#192]
As @skipmeister123 suggested in #65 we should add an option to show a little notification (similar to the resize info) that text has ben copied to the clipboard

**Comment by AndrewKralovec** [comment]
@felixse , should we reuse the re-size notification or create a separate one ?  The logic would stay mostly the same.

**Comment by skipmeister123** [comment]
If it was me doing the work, I'd want a general "notification" class, which I can invoke with a message (and maybe severity for an icon?).  That way, we open ourselves up to things like visual bells and stuff.

**Comment by AndrewKralovec** [comment]
Would you leave the notifications hooked up to the ViewModel, and then create class to do the logic or would you create an custom control? 

If its the former, does that class go under services dir or should it kept in the view model dir ?

**Comment by skipmeister123** [comment]
As a user, I don't care.  I would say that we may want a class, so that we could have multiple notifications (a bell chimes as you're resizing the window, for example.)

**Comment by AndrewKralovec** [comment]
Okay, I'll give this task a shot as my second ever commit. I moved the Overlay logic into a Overlay class,(since we already use a notification class for the toast). Once i figure out why the view model is not binding to the overlay class attributes, it'll be easy to extend it to show an overlay for the copied text and whatever else its needed for. 

https://github.com/AndrewKralovec/FluentTerminal/tree/DEV/CopiedTextOverlay

**Comment by felixse** [comment]
You are having problems with the bindings because your properties are not emitting the NotifyPropertyChangedEvent. I think the Overlay should actually be a ViewModel, that way you can inherit from ViewModelBase, then you can use the Set(ref _field, value) method to update the underlying field and raise the event.

**Comment by AndrewKralovec** [comment]
@felixse , Yeah i believe you are correct. I was thinking the same after i developed out the class. I appreciate the input. Most of my experience is in ASP.NET Core, and i hope to become better at Universal apps contributing to the project. 

I don't however, think it would be a good idea to repeat the overlay control elements for different overly information. I'll have to figure out how to pass the resize values to the control via an event, and not pass them as fields, otherwise whats the point of creating a control. You could just rename the resize methods to something generic and just changing the text for the desired overlay, be it the resize text, copied text, etc.  

Once again thanks for the responses, @felixse , @skipmeister123. This is great project and I appreciate the ability to contribute.
