### ISSUE TITLE
Add 'Choose Shell' menu for opening a new tab

### ISSUE THREAD

**Issue by yrccondor** [felixse/FluentTerminal#218]
It seems like that the only way to open a new tab with a shell that is not set as the default shell is using shortcuts. It will be better if there is a menu  to choose shell by listing available shells when right click the 'New Tab' button.

Please consider about it, thanks.

**Comment by felixse** [comment]
Good point, I think we can address this in context of #196

**Comment by ShubhamBelwal** [comment]
@felixse Can we have a drop-down list like the new windows-terminal, where we can see all the profiles we have configured? It would make opening a new non-default shell very easy compared to the current method.
I would suggest a Button similar to windows terminal, available in the Top Nav Bar, instead of a list available in sidebar, as proposed in [this comment](https://github.com/felixse/FluentTerminal/pull/196#issuecomment-524619505).

Just my personal opinion on how I would like to see the list of shells.

**Comment by Nisgrak** [comment]
Any updates about this feature?

**Comment by felixse** [comment]
Next version will list all profiles in the new tab/window menu
