### ISSUE TITLE
Is there a possibility to restore the last session?

### ISSUE THREAD

**Issue by xeranas** [felixse/FluentTerminal#285]
I wonder can I configure FluentTerminal to save my current opened tabs (with custom names and shells directories)? So I could recover setup quickly after PC restart.

**Comment by skipmeister123** [comment]
That would be a feature request.  I think you'd be pretty limited in how this would function, though.  We likely wouldn't be able to do ssh connections, run programs, or cd to directories due to a plethora of limitations.  If, however, you wanted to have a CMD, PowerShell, and WSL tab all open up... that should be something that could easily be accomplished.

**Comment by xeranas** [comment]
> wouldn't be able to cd to directories

Bummer...

What about if there would be the ability to define some sort of json file with ability to import it where it would contain tab name, shell type and init script which would be executed once tab ready. 

```
tabs {
  {
    tabName: 'fooBar',
    tabType: 'PowerShell',
    initScript: 'cd C:\barFoo'
  },
  {
    tabName: 'fooBar2',
    ...
  }
}
```
Does same limitation would still apply?

**Comment by skipmeister123** [comment]
You can already define a profile with custom arguments. At this time, 
there's no way to automatically launch more than one profile on startup, 
though.

**Comment by xeranas** [comment]
Understood, 
I guess for my case it would be sufficient default tabs described at #214 enhancement.

Thank you for your time, I think ticket can be closed for time being.
