### ISSUE TITLE
Feature Request: Enable different clipboard modes

### ISSUE THREAD

**Issue by LinqLover** [felixse/FluentTerminal#298]
When I used cmd/powershell before I knew FluentTerminal, I was used to highlight something using the mouse and press the right mouse button to copy it. After that - not being any longer in selection mode - I pressed the right mouse button again to paste the selected text in the input line.

I would love to see this feature coming to FluentTerminal.

Also, you could consider a setting that, if activated, makes pressing Enter in selection mode resulting into copying the selection instead of prompting the current input line.

**Comment by skipmeister123** [comment]
You can change the right click behavior in the settings. Will you check 
that and see if it suits your needs?

**Comment by TChristoph** [comment]
I am aware of this setting, but it currently only allows one _static_ association of the mouse buttons. I propose to introduce a selection mode as known from cmd & Co., so that the right mouse buttons behave dynamically: does Copy in selection mode, but does Paste in normal mode.

For more information, see https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc978582(v%3dtechnet.10).

**Comment by skipmeister123** [comment]
I think I see what you're getting at. That does sound nice.
