### ISSUE TITLE
Shortcuts to open a new tab with a given profile

### ISSUE THREAD

**Issue by Riebart** [felixse/FluentTerminal#37]
The customized new-tab feature is great, but it would be even slicker to be able to shortcut that with a keyboard key combination to directly launch a new tab of the specific kind. Like ConEmu's tasks, being able to bind `Ctrl+Shift+P` to launch a new tab with my PowerShell profile would be perfect (with the default being my WSL, for example).

This feels like a nice simple one for me to get started on in a fork.

**Comment by skipmeister123** [comment]
That does sound pretty easily to implement, but there might be conflicts
with custom profiles. For example, setting a shortcut to open a tab for a
custom profile, then removing said profile.

Hans Kokx

**Comment by Riebart** [comment]
Fair point. Seems like a simple corner case to handle, but a good one to point out nonetheless.

**Comment by skipmeister123** [comment]
Perhaps a good compromise would be a shortcut key specific to each profile?
When the profile is removed, the shortcut does nothing.

Hans Kokx

**Comment by felixse** [comment]
Yes, I would also suggest to add the shortcut to the profile.

@Riebart  PRs are always welcome 😃

**Comment by Riebart** [comment]
I'm working on this, getting close to having a PR ready.

**Comment by felixse** [comment]
I did some bigger changes to architecture this weekend, let's hope this will merge well 💀 

Some comments on your code so far:
- I wouldn't reuse KeyBinding and Command here. Just create some similar model class that has an Guid for the shellProfile instead of the Command. 
- I think we can keep this a lot cleaner if we don't mix it up with the command keyBindings in general.
we could then just pass a collection of these ShellShortcutKeyBinding or whatever we name it to the view, and there just also loop through this collection and invoke something like openTabWithShellProfile(id) on the bridge.
- For the view I would just add it to the ShellProfiles page instead of the KeyBindings, I think this would be more logical, but correct me if I'm wrong here.
- When you pull the latest changes from master you might also see that I added the KeyBinding dialog to the IDialogService, so this should be easier to reuse now.

Oh and many thanks to your contributions to the documentation, I should have really elaborated this a bit more in detail 😄

**Comment by Riebart** [comment]
There's some good discussion points there, thanks for the comments! I'll finish the last couple things, merge in master, fix that merge (which will inevitably break things), and then make a PR. We can discuss the architectural parts and implications on the overall design in the PR thread.

**Comment by Riebart** [comment]
See #45 for the PR, and I've made a few comments on how this was architected, so it's worth sliding the conversation over to there.

**Comment by Riebart** [comment]
The vastly superior PR is #85 which is much better architected, and will be mergable once I get time to fix the tests that are failing.
