### ISSUE TITLE
No beeps

### ISSUE THREAD

**Issue by cjw296** [felixse/FluentTerminal#386]
Please disable, or at least add an option, to disable beeps from terminals.
I never want them.

**Comment by daviesalex** [comment]
+1. I tried turning them off in bashrc and so on, but whatever I do something is left that beeps. They are super annoying!

**Comment by felixse** [comment]
https://github.com/felixse/FluentTerminal/issues/113 Does any of this help?

**Comment by cjw296** [comment]
I think @daviesalex tried this already. Some people may want to change the sound used, but I think myself and Alex, at least, just want a setting to turn off all sounds, ever, not ever ever have any emitted under any circumstances, at all, for any reason, ever ;-)

**Comment by daviesalex** [comment]
Yeah, I found myself in a game of whack-a-mole (as that post indicates; you disable it in bash but not zsh; vim is different to emacs, etc.). I've almost got rid of all of them now, but every so often I get a beep in my headphones because i'm running something that isnt specifically configured to not beep, and its really annoying!

A way to globally shut this up would be amazing (if Powershell ignores it and we cant intercept it to stop it, I guess the best you can do is document that). I do think that would be better than everybody having to update their bashrc (and vimrc, and inputrc, and so on) on every machine they ever connect to.

**Comment by MaxRis** [comment]
It works for me to turn off sound on per console session (per tab) from Volume Mixer panel:

![2019-06-22_11-14-26-volume-mixer](https://user-images.githubusercontent.com/1928902/59961398-e5786000-94df-11e9-871c-699cbf3d1a7c.png)

What do you think about if to achieve muting on per tab basis by triggering Volume Mixer API programmatically for corresponding processes?
Since tabs/windows control will be refactored soon (switch to new control), we can start just with single global option to mute all new spawned "Console Window Host" processes.

**Comment by MaxRis** [comment]
Interesting that beeping doesn't happen for me at all if ConPTY is enabled for terminal session (by default ConPTY is disabled for PowerShell sessions)

**Comment by daviesalex** [comment]
Using the volume mixer API is fine by me - nice idea! 
I think we decided that we actively want to encourage people to use winPTY for many other reasons, so I dont think we care about ConPTY.

**Comment by MaxRis** [comment]
Demo solution that mostly works turned out to be tricky and not straightforward:

- Beep sound in most cases is generated by conhost.exe (started by WinPTY)
- conhost.exe starts its audio session only after beep is generated
- To mute conhost.exe via Mixer API it's required to generate beep sound first
- Mixer stores the last mute/unmute action on any conhost.exe audio session and launches new sessions with latest selected mode. For example, if user mutes some available conhost's audio session then all new conhost sessions will be mutes as well, even if they launched from completely different process.

Demo solution:

- Fluent on start of terminal session spawns cmd.exe process in background with command line to generate bell ring: `cmd.exe /k \x07`. Just after that Fluent catches process PID of spawned conhost.exe by bell ring from cmd.exe and mutes audio session. All further audio sessions by others conhost.exe are muted automatically.
- On very first start Fluent generates single beep to rigger conhost's audio sessions. ( How is that acceptable ? ). After OS restart happens the same thing.
- Have noticed that VIM installed on my Windows generates beeps through "System sounds" and is not muted by above solution.

All to all everything that goes through conhost.exe is muted by above solution. Except single beep on first start of Fluent.

MSI with demo: https://ci.appveyor.com/api/buildjobs/bp33koj44p5e8lr2/artifacts/MsiInstaller%2FFluentTerminalInstaller-v1.1.204.0-4fec30b.msi

**Comment by mjs** [comment]
Nice work getting things working this far!

I've done some investigation to see if I could arrive at a cleaner solution but I wasn't able to. It's a shame that conhost has to make a sound to create the session before it can be silenced but I went quite deep into the Window Core Audio APIs (as I'm sure you did as well) and I don't see another way to do it.

Given that muting conhost.exe affects all future instances, I would suggest adding a global "Suppress terminal beeps" option to FluentTerminal (on the Terminal settings page), and doing the "play a beep, (un)mute the conhost" dance to a new systray process request. This can then be done when the systray process starts and also whenever the setting is changed. There's no need to tie this functionality to the startup of a particular terminal.

A hacky idea: you could hide the terminal beep required to mute conhost by temporarily turning down the volume on the audio endpoint (i.e. the speaker) while the beep is played. This should work except it could be annoying if some other audio is being played. Some music or a video call could end up being muted for a little bit. It might be worth a try though.

**Comment by MaxRis** [comment]
@mjs thank you for looking into it! Idea with muting output devices sounds great, will prepare another demo to get feedback.

**Comment by MaxRis** [comment]
@mjs new demo is available:

- Global settings option is added to mute terminal beeps
- On time of tray process startup global mute settings is applied
- Default audio device is muted while beep to trigger conhost audio sessions is generated

MSI: https://ci.appveyor.com/api/buildjobs/f7swwo65g64f9vl5/artifacts/MsiInstaller%2FFluentTerminalInstaller-v1.1.220.0-40d1fd8.msi

Changelist is ready for merge ( final PR into upstream will be from another branch ): https://github.com/jumptrading/FluentTerminal/compare/master...jumptrading:mr/no-beeps-fork?expand=1

**Comment by mjs** [comment]
@MaxRis I've tried out that MSI and I can't seem to get reliable behaviour from the beep setting. Every time I change the setting the global mute happens (good) but it doesn't seem to effect whether the terminal emits beeps or not.

My test has been to do `echo -e "\a"` in a WSL session. Sometimes it plays a beep, sometimes it doesn't, but this doesn't seem to correspond to the setting in FluentTerminal.

**Comment by mjs** [comment]
@MaxRis some logging in the `MuteTerminal` function might help to figure out what's going on.

**Comment by MaxRis** [comment]
> @MaxRis I've tried out that MSI and I can't seem to get reliable behavior from the beep setting. Every time I change the setting the global mute happens (good) but it doesn't seem to effect whether the terminal emits beeps or not.

@mjs changing "Mute terminal beeps" affects only future sessions and don't affect already launched terminals sessions. It's by design (mainly, because of OS API limitations).

**Comment by MaxRis** [comment]
@mjs seems I've just found the issue you've experienced!
it happens because last finished ConHost's audio session state is applied to the next launched ConHost's audio session. I didn't know about such behavior at all. It ruins current logic :(

**Comment by MaxRis** [comment]
@mjs updated version of implementation: https://ci.appveyor.com/api/buildjobs/7jp9qp7yj6e07q3d/artifacts/MsiInstaller%2FFluentTerminalInstaller-v1.1.286.0-530545b.msi

- Have added logging of muted conhost processes.
- `MuteTerminal` logic changed to iterate over all conhost processes ( including manually spawned ) and do attempt to mute audio session of each process.
