### ISSUE TITLE
Edge-like tabs

### ISSUE THREAD

**Issue by ZhouQD** [felixse/FluentTerminal#44]
This is a great app.

I think it would be nice if its tabs look like Microsoft Edge.

![image](https://user-images.githubusercontent.com/11922388/41511391-34790eee-7276-11e8-9d34-e8555f7d6ac8.png)

Backgrounds of the active tab and the terminal panel are the same. It looks more intuitive.

**Comment by skipmeister123** [comment]
@felixse this would solve the problem I was having. Is it possible to put
the tabs on the bottom? (Or have an option to do so?)

Hans Kokx

**Comment by felixse** [comment]
The tabs are pretty basic right now, so there is much room for improvement 

We could do edge like tabs by using the application theme background (black or white based on the current theme’s background) for the tab bar, and the theme background for the active tab, I will give this a try once I get to work on the tabs.

Tabs on bottom should be no big issue

**Comment by Linard11** [comment]
Would the new 'Sets'-Feature in Redstone 5 solve this if it would be supported?

**Comment by felixse** [comment]
Sets is great for combining different apps into one window, or to provide a tabbed experience to apps that just don't have them (like Explorer), but having tabs implemented on our own gives us advantages like configurable keyboard shortcuts for new tabs, confirm before closing, create a new tab with the shell selection dialog, etc.

Improvements to the tabs are coming soon, at least before RS5 😄

**Comment by neilsustc** [comment]
Good news. [WindowsCommunityToolkit v5.0.0](https://github.com/windows-toolkit/WindowsCommunityToolkit/releases/tag/v5.0.0) introduced TabView control which looks great!

[documentation](https://docs.microsoft.com/zh-cn/windows/communitytoolkit/controls/tabview)

![demo](https://docs.microsoft.com/zh-cn/windows/communitytoolkit/resources/images/controls/tabview/overview.gif)

**Comment by skipmeister123** [comment]
Can we tear tabs off into new windows with this?
--
Hans Kokx

**Comment by felixse** [comment]
Doesn't look to different from what we have right now, do you see any point in switching to this?

@skipmeister123 the problem with moving to new windows is about [serializing the renderer state](https://github.com/xtermjs/xterm.js/issues/595), not the tab control

**Comment by neilsustc** [comment]
Just FYI 😅

My two cents is it is "official" in a sense. Another difference is that the close button (on mouse hover) is more like edge-style comparing to the current one.

**current**
![image](https://user-images.githubusercontent.com/7588612/48020357-a69ec100-e12d-11e8-9cdd-8fb2dcd6fb3f.png)

**edge**
![image](https://user-images.githubusercontent.com/7588612/48020394-b6b6a080-e12d-11e8-94fa-e5c6b3beddb4.png)

**windows community tookits**
![image](https://user-images.githubusercontent.com/7588612/48020487-ed8cb680-e12d-11e8-93e1-72cff042bbf6.png)

**Comment by neilsustc** [comment]
> Can we tear tabs off into new windows with this?

@skipmeister123 Yes!

See https://twitter.com/XAMLLlama/status/1063526194191118336

**Comment by skipmeister123** [comment]
Perfect. Now we just need to sort out the split panes.
--
Hans Kokx

**Comment by MaxRis** [comment]
@felixse have investigated this in some details:

Mentioned above [TabView sample with Tear Off functionality](https://github.com/windows-toolkit/Sample-TabView-TearOff) is based on `TabView` control from `WindowsCommunityToolkit` and on good amount of additional logic to support `Tear Off` (description of additional custom logic can be found [there](https://github.com/windows-toolkit/Sample-TabView-TearOff#detecting-tab-drag)).

Fluent already has multi window functionality to run each separate window in its own thread (achieved by invoking `CoreApplication.CreateNewView().Dispatcher.RunAsync`). That's similar to `TabView sample with Tear Off`'s implementation, but such things as "communication" between windows in different threads, drag-in/out logic and so on, still should be incorporated in Fluent.

Since each window has it's own thread, it's not possible to move WebView instance between threads or access it from another thread. UWP seems doesn't provide API "to change" the thread for UI control.

Above limitation forces us to find a workaround:

- It was discussed possibility to serialize Xterm.JS state to be restored in new launched WebView. So far, I've tried to achieve serialization with [serialize-instance](https://www.npmjs.com/package/serialize-instance), but library has its own limitations and throws unhandled exceptions for Xterm.JS `Terminal` instance.
Having reliable serialization of Xterm.JS, seems, involves custom serialization/deserialization code to be added into core Xterm.JS implementation or maybe as specific add-on (if add-on has enough access to XTerm.JS internals.)

- Another approach is to move each XTerm.JS instance into additional separate WebView instance that will: be invisible for user; communicate with another visible WebView instance inside active UWP Window; efficiently update visible WebView instance with DOM changes; live for whole terminal session, while connected visible WebView might be destroyed when tab was teared off or window was docked as tab.

- Any other ideas?

I would prefer to try to keep XTerm.JS in separate WebView instance, but it's additional complication and potential performance drop reason.

cc: @mjs @peske

**Comment by felixse** [comment]
I don't think this 2 WebView approach will perform very good. Somebody is working on a [serialize addon for xterm.js](https://github.com/xtermjs/xterm.js/pull/2213) right now, maybe we can work with that.

**Comment by MaxRis** [comment]
@felixse yes, thanks, I've just discovered this ongoing work as well (it was published 5 hours ago).
That is very close to what we need! So we need to jump on xterm.js v4 beta build first!

**Comment by peske** [comment]
My opinion in short: since different FT windows are running in different UI threads, we must rely on xterm.js serialization. We cannot simply move views (tabs or WebViews) from one window to another. 

The only question for me is how significant advantage we have by running windows in separate threads? If we can reconsider that (if we can run all windows in the same UI thread), we can simply accomplish moving tabs from one window to another (or a new one), without using serialization at all.

I'm afraid that xterm.js serialization will come with some gotchas...

**Comment by felixse** [comment]
WPF is different in this regard because it allows for multiple windows on the same thread. UWP has a different [multi window concept](https://docs.microsoft.com/en-us/windows/uwp/design/layout/show-multiple-views) and an[ API more closely to WPF](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow) is still in preview even in 1903

**Comment by mjs** [comment]
+1 to trying out the the xterm.js serialization approach for moving tabs between windows. That seems the most viable to me. A single thread for all windows isn't going to be possible for a while and multiple WebView instances is likely to be too heavyweight.

Serialization of xterm.js's state will no doubt be tricky to get right but it still seems like the right thing to try first.

**Comment by mjs** [comment]
@felixse I think this can be closed now right?
