### ISSUE TITLE
Tabs which have been torn off do not load the theme properly

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#526]
![image](https://user-images.githubusercontent.com/1911919/65429826-d2c63d80-dde4-11e9-9f30-9fb1e7322eb3.png)

I tore off a new tab, and the theme wasn't loaded.

**Comment by mjs** [comment]
This is expected at the moment. Color information isn't currently preserved by the xterm.js serialisation plugin because xterm.js doesn't expose an API for this. New output will have color but any color that was there when the tab was moved is lost.

This will hopefully get better as xterm.js improves.
