### ISSUE TITLE
Change the background image

### ISSUE THREAD

**Issue by ustcfdm** [felixse/FluentTerminal#539]
For now the background is pure color. Can we set an image as the background? Here are some examples.

![image](https://user-images.githubusercontent.com/12667807/66150136-28b39600-e5da-11e9-87da-504994eed8e1.png)

![image](https://user-images.githubusercontent.com/12667807/66150291-74663f80-e5da-11e9-956e-b3cff3d77f5f.png)

**Comment by YohskDista** [comment]
Hi,
I will be happy to work on this issue. Do you think this is part of the theme or it should be in the in the settings (section `Terminal`) ? I think it's more logical to put it in the `Terminal` section but I just want to know your opinion about it.

Also for the image selection, do we need to save it in a specific folder in case of the deletion of the image ?

Best regards.
Leonardo

**Comment by felixse** [comment]
Thanks for picking this up 👍 

I think making it a part of theme makes it more flexible (like different themes with different images for different profiles). In regard of saving I would just put it somewhere in roaming storage. Also think about theme import/export. We could base64 encode it into the flutetheme file.

**Comment by YohskDista** [comment]
No problem, it's an interesting project 👍 

Ok to put the images in the theme but I think it's not a good idea to put the images in the roaming storage. Microsoft says that the roaming storage it's for a little amount of data (like the user settings, or little files) and the images that the user can import could be very heavy.

Also I was thinking to this solution when we import an image :

1. In the theme settings we can browse to files and select a picture
1. Copy the selected image in the LocalCache folder so that we can show the image as preview in the settings window.
1. When the user click on `Save` button we will move the image in a `Image` folder located in the `Local` storage file.

Otherwise to avoid the step with the `LocalCache` folder we need to add capabilities to the application so that we can access to the user documents.

What do you think about this ?

**Comment by felixse** [comment]
I guess images are still considered small enough. Problem is that themes are stored in roaming settings, so people might end up with missing background images on other computers.

I think we can skip the LocalCache step by just keeping it in memory until we save it.

**Comment by YohskDista** [comment]
My bad, the images can be put in the roaming folder according to Microsoft doc :+1:

The problem of the preview image in the settings it's that we cannot show files that aren't in the folder of the application unless we activate the `broadFileSystemAccess` ([StackOverflow](https://stackoverflow.com/questions/54091707/how-to-display-image-form-local-forder-uwp)). That's because our URI is a `C:\....\file1.png` and it should be more like `ms-appdata:///.../file1.png`

**Comment by felixse** [comment]
We can just load the file content into memory, that should do it

**Comment by YohskDista** [comment]
I found a kind of solution, I will propose you something until tomorrow.

Sorry to ask but I still don't know where I am supposed to make a branch. Master cannot be started because of the `Package.appxmanifest` that is not up to date (some permission are missing in the file I think).
To test my modifications I started with the branch `Dev/UWPRenderer` that was working correctly but I noticed that it is an old branch. Can you please help me so that I can make the PR?

**Comment by felixse** [comment]
Master should be fine. Did you set up FluentTerminal.Package as the startup project?

**Comment by YohskDista** [comment]
Here we go, that was the problem, I was targetting the App project. Thank you 👍
