### ISSUE TITLE
UI issue with WSL

### ISSUE THREAD

**Issue by Jangmingjin** [felixse/FluentTerminal#565]
![image](https://user-images.githubusercontent.com/28175935/67755258-cdf34a00-fa72-11e9-8455-fbb254354bdc.png)
![image](https://user-images.githubusercontent.com/28175935/67755308-e499a100-fa72-11e9-917b-fd678a6d1aa6.png)
There are black icon remained in background from OS icon
And it overwritten in content
Is there any idea for this issue?
Thanks

**Comment by Jangmingjin** [comment]
I am using powerlevel10k and Hack Nerd font

**Comment by IgnusG** [comment]
<img src="https://user-images.githubusercontent.com/6438760/68186634-8bd08800-ffdf-11e9-9c5f-2005c20c39e4.png" align="right">
This happens because of the width of the character/image displayed. The terminal view probably doesn't refresh the cell next to where the icon was displayed. I have the same issue on WSL with regular tab arrows (⇥) that span 2 characters.

**Comment by Jangmingjin** [comment]
But cmder has not such issue
Is there any solution to resolve this issue?

**Comment by IgnusG** [comment]
I suspect it's a problem with ConPTY. Disabling it removed the issue, but you loose true color support :(
