### ISSUE TITLE
Activity indicators on tabs

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#60]
If I have multiple tabs open and there's activity in one of them, there needs to be some sort of a visual indicator on the tab itself.  This could be in the form of a subtle highlight or a prepended bell icon, perhaps.

**Comment by felixse** [comment]
Nice idea 👍

**Comment by Riebart** [comment]
With the new tab colour themes, we could indicate this by flashing between active and inactive background at some non-annoying rate. My gut tells me the bulk of the detection logic, or at least the detection event, is in https://github.com/felixse/FluentTerminal/blob/bfad59fa7a609acaaabbacb3ee29390e2747b275/FluentTerminal.App.Services/Implementation/TrayProcessCommunicationService.cs#L83

**Comment by felixse** [comment]
I thought about just adding a nice icon where the close button would be (since the tab colors PR only the active tab shows the close button to better emphasize which one is active), you think that might be enough?

Detecting should be no big problem, terminalOutput callback is definitevely the right place

**Comment by skipmeister123** [comment]
I'd have to see a mock-up, but it's probably ok.
--
Hans Kokx
