### ISSUE TITLE
Warning: Identity file 'C:\Users\User\sshkey' not accessible: No such file or directory.

### ISSUE THREAD

**Issue by dual-oo** [felixse/FluentTerminal#685]
Hi,

after Update to 0.7.0.0 I can't acces via ssh key file.
Warning: Identity file 'C:\Users\User\sshkey' not accessible: No such file or directory.

Permissions are set to the user + admin-group (Administrators)

thanks for help

**Comment by monkeyking** [comment]
I met the same problem..

**Comment by TailyFair** [comment]
Having same issue

**Comment by dogik** [comment]
same here

**Comment by zcrbb** [comment]
Having same issue 😥 i love this project but it is a fatal problem.

**Comment by maxhora** [comment]
Can't repro so far. Generated key file with
`ssh-keygen -t ecdsa -b 52`
Added to `ssh-agent` with
`ssh-add .\.ssh\id_ecdsa`
Able to connect from Fluent to linux box without issues.

**Comment by TailyFair** [comment]
I would like to point out, that this issue only happens when using `SSH profiles`.

**Comment by maxhora** [comment]
@TailyFair thank you! Was able to repro this finally

**Comment by maxhora** [comment]
@TailyFair are you using SSH profile with "Use Mosh" option been enabled?

**Comment by maxhora** [comment]
@TailyFair please ignore my above question.

It is turned out we have started to use single quote around path to identity file, but OpenSSH doesn't like this. PR with fix https://github.com/felixse/FluentTerminal/pull/698

Important note: You need to "re-save" your SSH profiles to trigger new generation of correct ssh arguments. For example, you can toggle "Use Mosh" ON/OFF on each profile and press "Save" multiple times.

**Comment by dual-oo** [comment]
got this error still with 0.7.1.0
