### ISSUE TITLE
Looking for feedback: Tab-styling per theme

### ISSUE THREAD

**Issue by Riebart** [felixse/FluentTerminal#71]
Been playing with what it will take to style tabs with the theme they are on (ties in with #28). Got a reasonable PoC done, but need a bit more work.

The way this works is that there will be a hanful of new values per theme, and the defaults (if unset) will be to use the current behaviour of following the Windows theme. The full list of colours that it could support is:

- Inactive tabs
  - Background
  - Foreground
  - Underline
  - Hover background
  - Hover foreground
  - Pressed background (foreground will match the hover foreground)
- Selected tab
  - Background
  - Foreground
  - Underline
  - Hover background (foreground be unchanged)
  - Pressed background (foreground be unchanged)

![image](https://user-images.githubusercontent.com/1278193/44304354-76f6ce80-a31f-11e8-9dd7-5b9310c2d1d8.png)

Thoughts? Suggestions? Things to do still:

- Convert the colour selection to match the existing grid style, since I was originally only planning to support a few colours, but with 11 it's time to move to just a box grid
- Need a good way of indicating in the UI via a ColourPicker that no colour has been chosen (the underlying value is `null`), so the system colours will be used.
  - This also needs a "clear colours" button for the tabs, to reset them back to the system defaults.

I'll update this issue when I push the code to my fork.

**Comment by Riebart** [comment]
The idea is that you'd be able to leave them as windows default, or override. Leaving the values unset would let them follow the Windows default, and you'd be able to do that on a per-value basis.

The use case I have in mind is that I work on remote machines a lot, and this combined with the per-profile shortcuts that I need to rewrite would be excellent visual reminders of which tabs on which machines.

**Comment by skipmeister123** [comment]
Ok, sure. I dig it.
--
Hans Kokx

**Comment by Riebart** [comment]
Code pushed to https://github.com/Riebart/FluentTerminal/tree/tab_theme_colours. See the commits for specific TODO items remaining. Currently supports the default "leave it to Windows" behaviour, and overriding any parts separately of it with specific colours.

**Comment by felixse** [comment]
Looks like a nice feature 😃 

Some comments:
- We could solve some problems by adding a Converter that returns the color if not null, or else looks up the desired default color (we can pass the resource key as ConverterParameter) from the resources. The problem I see right now is that we most likely break the default colors for light themes, and it would also keep or services and viewModels cleaner
- We should move 'underline selected tab' to the theme, just to keep it all in one place.
- The color selection looks fine actually, I guess with the grid it would be too difficult to see which color is used for what. We could also expand to the last line (foreground, selected, cursor etc)of the current color grid in the same way, since nobody knows what they do until they mouseover it.

**Comment by Riebart** [comment]
I am just sorting out some issues with the behaviour of some of the colours, then I will make a PR and we can figure out what we want to do for the first iteration of the feature. Once it is in master, then it is easy for more people to contribute the other ideas.

**Comment by Riebart** [comment]
Effectively closed by #73
