### ISSUE TITLE
Choose "Traditional Chinese", but it shows "Simplified Chinese"

### ISSUE THREAD

**Issue by TSUNKNOWN** [felixse/FluentTerminal#716]
As the title.

![image](https://user-images.githubusercontent.com/31957845/79064777-65292280-7cde-11ea-8019-cc70e05efbcd.png)

**Comment by felixse** [comment]
are only some of them simplified or all? And if you select simplified Chinese do you see the correct translations?

**Comment by TSUNKNOWN** [comment]
My Win10 system uses Traditional Chinese.

"System Default" shows all Simplified Chinese, which is the same when I select "Simplified Chinese".

"Traditional Chinese" shows Simplified Chinese as well. The little difference is there would be English in some part. (like the img below)
![image](https://user-images.githubusercontent.com/31957845/79120892-9b41d180-7dc6-11ea-9f78-2e1cf880e565.png)

Hope this problem can be fixed asap. Thanks!

**Comment by felixse** [comment]
Ok, so the English text is because translations were missing when this was released. And the settings menu item on this screenshot has the same signs in both simplified and traditional Chinese. Don't know if this is correct though. Maybe have a look at the translations [here](https://poeditor.com/join/project/TfKNIt826z) and check for those occurrences of simplified Chinese when traditional is selected

**Comment by TSUNKNOWN** [comment]
I've checked the translations. It seems OK for Traditional Chinese.
The part of translation (where the terminal shows Simplified Chinese) is OK though.
Maybe the code connected to the wrong translation?

Thanks for replying.
and I'll use some free time to help translation to make the terminal perfect haha

**Comment by felixse** [comment]
OK, maybe this has improved since the last released. Current master looks like this:

zh-Hant:
![image](https://user-images.githubusercontent.com/30559812/79253758-09000300-7e84-11ea-90fe-bb88fa86c27e.png)

zh-Hans:
![image](https://user-images.githubusercontent.com/30559812/79253796-16b58880-7e84-11ea-91d1-80ae3abe5ba1.png)

**Comment by TSUNKNOWN** [comment]
I'm sorry to say that there's still something wrong.

First, 
Traditional Chinese = 繁體中文 = zh-hant ('t' for 'traditional')
Simplified Chinese = 简体中文 = zh-hans ('s' for 'simplified')
Thus, the two images above have to be exchanged.

Second, only the red rectangle parts are Traditional Chinese, which means there's almost Simplified Chinese.
![79253758-09000300-7e84-11ea-90fe-bb88fa86c27e](https://user-images.githubusercontent.com/31957845/79257736-a545fc00-7ebc-11ea-88c7-a740ebc60073.png)
![79253796-16b58880-7e84-11ea-91d1-80ae3abe5ba1](https://user-images.githubusercontent.com/31957845/79257738-a6772900-7ebc-11ea-9397-c9eab5a1accb.png)

In the translation page, there are 3 Chineses. "Chinese (TW)" is the only Traditional Chinese.
![image](https://user-images.githubusercontent.com/31957845/79258089-33ba7d80-7ebd-11ea-90c7-a035154b7dc9.png)

**Comment by felixse** [comment]
ok, so apparently this got mixed up:
![image](https://user-images.githubusercontent.com/30559812/79262375-7e260500-7e91-11ea-9b03-54c44e8928bb.png)

Chinese (TW) is currently not used since it's not translated enough.
Also the on/off labels for switches are translated by the system.

So it would be correct if I swap those two and we ignore the on/off labels? The remaining issues seem to be in the translations on POEditor if I understand correctly

**Comment by TSUNKNOWN** [comment]
Yeah, I believe that's the problem, and the swap can solve it (on/off label can be shown correctly as well).
I've almost completed the translation. Its completion rate is 87% now (may be higher tomorrow). So, I believe that's a good choice to use it.

**Comment by TSUNKNOWN** [comment]
I've complete the Traditional Chinese translation (100%). Thanks.

**Comment by felixse** [comment]
So this is a third translation now, zh-TW (臺灣華語)?

**Comment by TSUNKNOWN** [comment]
Not actually.
Traditional Chinese is used by Taiwan, Hong Kong, etc. Taiwan is just one of them.
Thus, I think 2 translations of Chinese is enough.
1. zh-hant (繁體中文) use "Chinese (TW)"
2. zh-hans (简体中文) use "Chinese" or "Chinese (simplified)" (no big difference, both are Simplified Chinese)

Thanks for fixing this!

**Comment by felixse** [comment]
OK, great. Thank you for looking into this. Regarding Chinese and Chinese (simplified) on POEditor: I think we should delete one of them to avoid confusion. Which would you recommend keeping?

**Comment by TSUNKNOWN** [comment]
I think "Chinese (simplified)" is better because its name is more clear about the type. ( It seems no difference in the content.)
BTW, I discovered the name and icon of "Chinese (TW)" is changed in POEditor. The new name is reasonable, but the icon is not suitable because China don't use Traditional Chinese. Thus, I think the previous icon is better (since Taiwan is one of the biggest country where uses Traditional Chinese).

**Comment by TSUNKNOWN** [comment]
I think "Chinese (simplified)" is better because its name is more clear about the type. ( It seems no difference in the content.)
BTW, I discovered the name and icon of "Chinese (TW)" is changed in POEditor. The new name is reasonable, but the icon is not suitable because China don't use Traditional Chinese. Thus, I think the previous icon is better.

**Comment by felixse** [comment]
OK, reverted to Chinese (TW) and deleted one of the simplified Chinese. This will be included in update in a few days

**Comment by mrchar** [comment]
hello, is there any new progress? and  how soon will it be released?

**Comment by felixse** [comment]
There are some packaging issues which are being looked at right now, but I cannot give you any ETA
