### ISSUE TITLE
Integrated Terminal in VS Code

### ISSUE THREAD

**Issue by malpaso** [felixse/FluentTerminal#736]
Is it possible to use Fluent as the integrated terminal in VS Code? Apologies if this has been clarified somewhere but I couldn't find it.

**Comment by felixse** [comment]
You mean configure it as the external terminal? Replacing the terminal within VS Code is not possible.

**Comment by TheMisir** [comment]
You could use fluent terminal as a external terminal (for open new terminal command) but you can't use it for integrated one. Because fluent is terminal emulator not an shell (like powershell, cmd, bash, ...).

**Comment by feyzullahyildiz** [comment]
> You could use fluent terminal as a external terminal (for open new terminal command) but you can't use it for integrated one. Because fluent is terminal emulator not an shell (like powershell, cmd, bash, ...).

I am already using Cmder integrated terminal in vscode. You guys can check this.
https://winsmarts.com/using-cmder-as-integrated-shell-in-vscode-c3340714fe3c

**Comment by TheMisir** [comment]
I don't think cmder and fluent terminal is the same thing. Visual studio is
emulating shells in its terminal (handling std::cin and std::cout streams).
I don't think it supports GUI apps. You could try setting integrated
terminal executable path but I think it will show fluent terminal window
instead of emulating terminal.

Could you let us know why you would like to use fluent terminal in visual
studio?

--
Misir Jafarov

**Comment by felixse** [comment]
I think the confusion here is that Cmder is a package that contains ConEmu (Something like Fluent Terminal) and some profiles (which besides other things themes the prompt to use the lambda symbol). 

The guide @feyzullahyildiz posted describes how to use the profile with vscode instead of ConEmu. 

Since Fluent Terminal does not provide any profiles there is nothing that can be used in vscode.

If you are trying to get vscode's terminal to look similar to the screenshot in the readme, have a look here: https://github.com/felixse/FluentTerminal/wiki/FAQ#how-can-i-achieve-the-look-of-the-terminal-in-the-readme (obviously font's and colors need to be configured in vscode instead, but the PowerShell modules are not particular to any terminal application)
