### ISSUE TITLE
Crashes on authorization

### ISSUE THREAD

**Issue by Mystic8b** [felixse/FluentTerminal#786]
Guys, another problem came out.
If you close the terminal at the stage of entering the password for ssh (or for the key), the application crashes.
Like in the screenshot. After clicking on X, it does not close, but crashes.
![image](https://user-images.githubusercontent.com/35394377/83930854-5f156680-a7a2-11ea-81ba-3e7ff561817f.png)

**Comment by maxhora** [comment]
@Mystic8b thank you for the report.
Could you please give some details why do you think it is crashes?
I can't repro the crash, but delay on closing really occurs. Also if I try to close ordinal `cmd.exe` with pending ssh login prompt, it behaves with similar delay. So far I would think it is only the delay, but not a crash. And since it happens because of `cmd.exe` internals, it is not related to Fluent.

**Comment by Mystic8b** [comment]
Interestingly, yesterday I observed a restoration of the size and position of the window to the default after the steps described above, I thought it was talking about crash. But today this does not happen, and as you say, the window just closes slowly (which is probably also not normal behavior, but in general nonsense).
Okay, if I can reproduce the situation like yesterday (size settings, etc. are reset) - I will write. Thank.
