### ISSUE TITLE
Open new window on Shift+Click Taskbar icon, left-click on a new desktop

### ISSUE THREAD

**Issue by Riebart** [felixse/FluentTerminal#81]
Using multiple desktops is nice, but clicking on the FT icon in the task bar when on a desktop without an FT window snaps me to a window with an FT window (the most recently used one? Not sure, actually). It would be nice to be able to open a new window if I click the taskbar icon on a desktop without an FT window, or shift-click the task bar icon.

I'd take a stab at this, but I really have no clue how to detect these events in a UWP app, or how best to handle them.

**Comment by felixse** [comment]
I'm not sure if this is even possible right now, I guess other UWP apps like Mail would behave similar. Maybe we can get there by adding support for [multiple instances](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp), but that would be pretty much a rewrite of the multi window stuff, and raises us to 1803 as a minimal version

**Comment by skipmeister123** [comment]
I'd like to point out that Edge has the desired behavior.


--
Hans Kokx
On 9/20/2018 7:34:31 AM, Felix <notifications@github.com> wrote:
I'm not sure if this is even possible right now, I guess other UWP apps like Mail would behave similar. Maybe we can get there by adding support for multiple instances [https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp], but that would be pretty much a rewrite of the multi window stuff, and raises us to 1803 as a minimal version

**Comment by felixse** [comment]
Should not be that hard. Only thing we must think about is propagating changed settings to the windows. We are using events right now since everybody is using the same instance of SettingsService, but with multiple instances we need to send it via AppServiceConnection. 

Implementing mutliple windows with secondary views was a pain, but that was all I had back then 😄 
Rewrititing this might as well fix some bugs like #62
