### ISSUE TITLE
Forced to start up on boot.

### ISSUE THREAD

**Issue by sarahkittyy** [felixse/FluentTerminal#937]
![image](https://user-images.githubusercontent.com/31551546/126053709-79a7b2cd-995b-4cbc-b395-f9c54245d87d.png)

Why is this happening? This is happening with Windows Terminal too. Is there a registry key / entry in group policy that is forcing this? It's also locked in windows settings. 

![image](https://user-images.githubusercontent.com/31551546/126053726-08df822b-1df0-470f-9e53-2dec1863a490.png)

**Comment by hanskokx** [comment]
Hey @sarahkittyy!  Thanks for using FluentTerminal :)

I think you're right in thinking that this isn't a FluentTerminal issue.  It's probably, as you've surmised, a Windows policy or something.

There's a policy in [User Configuration > Administrative Templates > System > Logon] called "Run these programs at user logon".  I'd start by checking that.

It's also less likely that there's a logon script.  You can find that in [User Configuration > Windows Settings > Scripts (Logon/Logoff)]. (There's also a system-wide policy under Computer Configuration).

A bit less likely, since it explicitly states, "Enabled by policy," is the registry.  You can find the startup items in the following hive: Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run

Let me know if anything here helps!

**Comment by sarahkittyy** [comment]
@hanskokx Yeah, you're right, none of those settings existed though, however I've just entirely reinstalled windows at this point and that has fixed the issue. Painful, but necessary. 

https://superuser.com/questions/1663242/uwp-apps-locked-out-of-changing-startup-options/1663397#1663397
